# Generated by Django 5.2.12 on 2026-04-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantite', models.PositiveIntegerField(help_text='Nombre de poches')),
                ('delai', models.DateField(help_text='Date limite')),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('cloturee', 'Clôturée'), ('satisfaite', 'Satisfaite')], default='active', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='accounts.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_recus', to='accounts.hopital')),
            ],
            options={
                'ordering': ['-date_don'],
            },
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='donations.demandeurgente')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='accounts.donneur')),
            ],
            options={
                'unique_together': {('demande', 'donneur')},
            },
        ),
    ]
