# Generated by Django 5.2.12 on 2026-04-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=300)),
                ('groupes_cibles', models.CharField(help_text='Ex: A+, O-, B+', max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='accounts.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.TimeField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='campaigns.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='accounts.donneur')),
            ],
            options={
                'unique_together': {('campagne', 'donneur')},
            },
        ),
    ]
